export const underReview = '#60aa4f'
export const responded = '#25a898'
export const accepted = '#ee2424'
export const cancelled = '#9e9e9e'
export const delivering = '#b66ac7'
export const received = '#edef7b'
export const rejected = '#ed1a41'
