# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
#  push:
#    branches:
#      - master
  pull_request:
    types: [opened]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.8.8
        with:
          heroku_api_key: "2d3d94a3-151a-4bb0-92ad-e1099e4dbb61"
          heroku_app_name: "testsme2020"
          heroku_email: "charleshoong97@gmail.com"
          branch: "master"
      - name: Run CI
        run: npm ci
      - name: Install NPM
        run : npm install
      - name : Run Build
        run: npm run build --if-present
