# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Pull Request Check

on:
  pull_request:
    types: [opened]

jobs:
  DeployToHeroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependency
        run: npm i
      - name: Dependency Integration
        run: npm ci
      - name: System Test
        run: npm test
